"""initial_schema

Revision ID: 632d4e74bb07
Revises: 
Create Date: 2026-02-25 18:53:54.311273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '632d4e74bb07'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('ACADEMIC_UPDATE', 'ANNOUNCEMENT', 'DEADLINE', name='notificationtype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_entity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_entity_id', sa.Uuid(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    op.create_index(op.f('ix_notification_type'), 'notification', ['type'], unique=False)
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'PROFESSOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_status'), 'user', ['status'], unique=False)
    op.create_table('chat_session',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('context_widow', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_session_id'), 'chat_session', ['id'], unique=False)
    op.create_index(op.f('ix_chat_session_is_active'), 'chat_session', ['is_active'], unique=False)
    op.create_index(op.f('ix_chat_session_user_id'), 'chat_session', ['user_id'], unique=False)
    op.create_table('document',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_type', sa.Enum('SYLLABUS', 'REGULATION', 'GUIDELINE', 'RESEARCH', name='documenttype'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_doc_type'), 'document', ['doc_type'], unique=False)
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    op.create_index(op.f('ix_document_title'), 'document', ['title'], unique=False)
    op.create_table('professor',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('office_hours', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_professor_department'), 'professor', ['department'], unique=False)
    op.create_table('student',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('registration_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('major', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('student_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_student_major'), 'student', ['major'], unique=False)
    op.create_index(op.f('ix_student_registration_number'), 'student', ['registration_number'], unique=True)
    op.create_table('user_notification',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_status', sa.Enum('PENDING', 'DELIVERED', 'FAILED', name='deliverystatus'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notification_delivery_status'), 'user_notification', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_user_notification_id'), 'user_notification', ['id'], unique=False)
    op.create_index(op.f('ix_user_notification_notification_id'), 'user_notification', ['notification_id'], unique=False)
    op.create_index(op.f('ix_user_notification_user_id'), 'user_notification', ['user_id'], unique=False)
    op.create_table('ai_interaction',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('action_executed', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('interaction_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_interaction_id'), 'ai_interaction', ['id'], unique=False)
    op.create_index(op.f('ix_ai_interaction_session_id'), 'ai_interaction', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_interaction_timestamp'), 'ai_interaction', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ai_interaction_user_id'), 'ai_interaction', ['user_id'], unique=False)
    op.create_table('course',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='coursestatus'), nullable=False),
    sa.Column('professor_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_code'), 'course', ['code'], unique=True)
    op.create_index(op.f('ix_course_id'), 'course', ['id'], unique=False)
    op.create_index(op.f('ix_course_status'), 'course', ['status'], unique=False)
    op.create_index(op.f('ix_course_title'), 'course', ['title'], unique=False)
    op.create_table('attendance_session',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_session_course_id'), 'attendance_session', ['course_id'], unique=False)
    op.create_index(op.f('ix_attendance_session_id'), 'attendance_session', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_session_starts_at'), 'attendance_session', ['starts_at'], unique=False)
    op.create_table('course_material',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_type', sa.Enum('PDF', 'DOCX', 'LINK', 'NOTE', name='materialtype'), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_material_course_id'), 'course_material', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_material_file_type'), 'course_material', ['file_type'], unique=False)
    op.create_index(op.f('ix_course_material_id'), 'course_material', ['id'], unique=False)
    op.create_index(op.f('ix_course_material_indexed_at'), 'course_material', ['indexed_at'], unique=False)
    op.create_table('documentinteraction',
    sa.Column('doc_interaction_id', sa.Uuid(), nullable=False),
    sa.Column('interaction_id', sa.Uuid(), nullable=False),
    sa.Column('doc_id', sa.Uuid(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('usage_order', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['interaction_id'], ['ai_interaction.id'], ),
    sa.PrimaryKeyConstraint('doc_interaction_id')
    )
    op.create_index(op.f('ix_documentinteraction_doc_id'), 'documentinteraction', ['doc_id'], unique=False)
    op.create_table('enrollment',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('ENROLLED', 'DROPPED', 'COMPLETED', 'WAITLISTED', name='enrollmentstatus'), nullable=False),
    sa.Column('enrollment_at', sa.DateTime(), nullable=False),
    sa.Column('last_grade_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_course_id'), 'enrollment', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollment_id'), 'enrollment', ['id'], unique=False)
    op.create_index(op.f('ix_enrollment_status'), 'enrollment', ['status'], unique=False)
    op.create_index(op.f('ix_enrollment_student_id'), 'enrollment', ['student_id'], unique=False)
    op.create_table('attendance_record',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attendance_session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendancestatus'), nullable=False),
    sa.Column('marked_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_session_id'], ['attendance_session.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_record_attendance_session_id'), 'attendance_record', ['attendance_session_id'], unique=False)
    op.create_index(op.f('ix_attendance_record_id'), 'attendance_record', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_record_marked_at'), 'attendance_record', ['marked_at'], unique=False)
    op.create_index(op.f('ix_attendance_record_status'), 'attendance_record', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_record_student_id'), 'attendance_record', ['student_id'], unique=False)
    op.create_table('grade',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_type', sa.Enum('EXAM', 'ASSIGNMENT', 'PROJECT', 'PARTICIPATION', name='assessmenttype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_assessment_type'), 'grade', ['assessment_type'], unique=False)
    op.create_index(op.f('ix_grade_enrollment_id'), 'grade', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_grade_graded_at'), 'grade', ['graded_at'], unique=False)
    op.create_index(op.f('ix_grade_id'), 'grade', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grade_id'), table_name='grade')
    op.drop_index(op.f('ix_grade_graded_at'), table_name='grade')
    op.drop_index(op.f('ix_grade_enrollment_id'), table_name='grade')
    op.drop_index(op.f('ix_grade_assessment_type'), table_name='grade')
    op.drop_table('grade')
    op.drop_index(op.f('ix_attendance_record_student_id'), table_name='attendance_record')
    op.drop_index(op.f('ix_attendance_record_status'), table_name='attendance_record')
    op.drop_index(op.f('ix_attendance_record_marked_at'), table_name='attendance_record')
    op.drop_index(op.f('ix_attendance_record_id'), table_name='attendance_record')
    op.drop_index(op.f('ix_attendance_record_attendance_session_id'), table_name='attendance_record')
    op.drop_table('attendance_record')
    op.drop_index(op.f('ix_enrollment_student_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_status'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_course_id'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_documentinteraction_doc_id'), table_name='documentinteraction')
    op.drop_table('documentinteraction')
    op.drop_index(op.f('ix_course_material_indexed_at'), table_name='course_material')
    op.drop_index(op.f('ix_course_material_id'), table_name='course_material')
    op.drop_index(op.f('ix_course_material_file_type'), table_name='course_material')
    op.drop_index(op.f('ix_course_material_course_id'), table_name='course_material')
    op.drop_table('course_material')
    op.drop_index(op.f('ix_attendance_session_starts_at'), table_name='attendance_session')
    op.drop_index(op.f('ix_attendance_session_id'), table_name='attendance_session')
    op.drop_index(op.f('ix_attendance_session_course_id'), table_name='attendance_session')
    op.drop_table('attendance_session')
    op.drop_index(op.f('ix_course_title'), table_name='course')
    op.drop_index(op.f('ix_course_status'), table_name='course')
    op.drop_index(op.f('ix_course_id'), table_name='course')
    op.drop_index(op.f('ix_course_code'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_ai_interaction_user_id'), table_name='ai_interaction')
    op.drop_index(op.f('ix_ai_interaction_timestamp'), table_name='ai_interaction')
    op.drop_index(op.f('ix_ai_interaction_session_id'), table_name='ai_interaction')
    op.drop_index(op.f('ix_ai_interaction_id'), table_name='ai_interaction')
    op.drop_table('ai_interaction')
    op.drop_index(op.f('ix_user_notification_user_id'), table_name='user_notification')
    op.drop_index(op.f('ix_user_notification_notification_id'), table_name='user_notification')
    op.drop_index(op.f('ix_user_notification_id'), table_name='user_notification')
    op.drop_index(op.f('ix_user_notification_delivery_status'), table_name='user_notification')
    op.drop_table('user_notification')
    op.drop_index(op.f('ix_student_registration_number'), table_name='student')
    op.drop_index(op.f('ix_student_major'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_professor_department'), table_name='professor')
    op.drop_table('professor')
    op.drop_index(op.f('ix_document_title'), table_name='document')
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.drop_index(op.f('ix_document_doc_type'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_chat_session_user_id'), table_name='chat_session')
    op.drop_index(op.f('ix_chat_session_is_active'), table_name='chat_session')
    op.drop_index(op.f('ix_chat_session_id'), table_name='chat_session')
    op.drop_table('chat_session')
    op.drop_index(op.f('ix_user_status'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_notification_type'), table_name='notification')
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
